openapi: 3.0.3
info:
  version: 1.0.0
  title: Team API
  description: Team api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/employees:
    x-router-controller: employersController
    get:
      description: Returns all teams
      operationId: getEmployees
      responses:
        200:
          description: Team list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/employee'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'     
  /api/v1/employees/{value}:
    x-router-controller: employersController
    get:
      description: Returns a single team by its id
      operationId: findByvalue
      parameters:
        - required: true
          name: value
          description: id of the team to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Team found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/employee'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    team:
        type: object
        required:
          - value
        properties:
          genre:
            type: string
          live_with:
            type: number
          territory:
            type: string
          employee:
            type: number
          value:
            type: number
          year:
            type: number
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true